### ISSUE TITLE
Notifications with notifu does not work for onFailWithoutProject

### ISSUE THREAD

**Issue by michaldo** [jcgay/maven-notifier#17]
Maven 3.3.3, maven-notifier-1.9, notifu-1.6, windows 10.

I made a pom.xml unparseable. My output looks like:

> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\Users\micdom\idea\BPP\pom.xml: start tag unexpected character " (position: TEXT seen...

but instead of receive notifu message I got notifu internal error window  with message: **Unrecognized argument '(position:'**

**Comment by jcgay** [comment]
Thanks for the report!

It seems the problem appears when the error message contains a `"`.
I'm looking into it.

**Comment by jcgay** [comment]
I have deployed a new SNAPSHOT with a fix here: https://oss.sonatype.org/content/repositories/snapshots/fr/jcgay/maven/maven-notifier/1.9.1-SNAPSHOT/

Can you give it a try @michaldo ?

Thanks!

**Comment by michaldo** [comment]
Resolved
thx

**Comment by jcgay** [comment]
Thanks for giving it a try!
I'll release it today.
Le 12 avr. 2016 8:20 AM, "Michal Domagala" <notifications@github.com> a
écrit :
