### ISSUE TITLE
Configure notification duration

### ISSUE THREAD

**Issue by tisaksen** [jcgay/maven-notifier#26]
Is there a setting in maven-notifier.properties to set how many seconds the notification should be visible?

**Comment by jcgay** [comment]
There is no such property at the moment.

In [send-notification](https://github.com/jcgay/send-notification/) you can control a 'timeout' for a notification : https://github.com/jcgay/send-notification/issues/9
This timeout usage is also dependent on which notifier is used...

`maven-notifier` should set this timeout on the `Application` in https://github.com/jcgay/maven-notifier/blob/36fc6c5298cc7fbdef85c312de47c35af65997cb/src/main/java/fr/jcgay/maven/notifier/sendnotification/SendNotificationNotifier.java#L29

**Comment by jcgay** [comment]
The timeout can now be set but I don't think it will do what you want 😇.
I'll have a look in send-notification to see if a duration can be added (depending on the notifier)
